---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - name: sync-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OS_AUTH_URL
              value: {{ printf "%s.%s.%s" "https://iam" .Values.config.tCloudRegion "otc.t-systems.com/v3" | quote }}
            - name: OS_REGION_NAME
              value: {{ .Values.config.tCloudRegion | quote }}
            - name: OS_DOMAIN_NAME
              value: {{ .Values.config.tCloudDomainName | quote }}
            - name: OS_PROJECT_ID
              value: {{ .Values.config.tCloudProjectId | quote }}
            - name: KEEP_CERT_REGEX
              value: {{ .Values.config.keepCertRegex | quote }}
            - name: OS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.credentials.existingSecret.name }}{{ .Values.credentials.existingSecret.name }}{{ else }}{{ .Release.Name }}-t-cloud-credentials{{ end }}
                  key: {{ if .Values.credentials.existingSecret.name }}{{ .Values.credentials.existingSecret.accessKeyKey }}{{ else }}OS_ACCESS_KEY{{ end }}
            - name: OS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.credentials.existingSecret.name }}{{ .Values.credentials.existingSecret.name }}{{ else }}{{ .Release.Name }}-t-cloud-credentials{{ end }}
                  key: {{ if .Values.credentials.existingSecret.name }}{{ .Values.credentials.existingSecret.secretKeyKey }}{{ else }}OS_SECRET_KEY{{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
