---

{{- if not .Values.credentials.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-otc-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  OS_ACCESS_KEY: {{ .Values.credentials.accessKey | b64enc | quote }}
  OS_SECRET_KEY: {{ .Values.credentials.secretKey | b64enc | quote }}
{{- end }}
